"""Builds small MP4/M4A test fixtures with genuinely decodable content.

Part E replaced the owned demuxer and decoders with FFmpeg, so a real
decoder now sits behind every fixture this suite loads: hand-rolled boxes
with zero-filled or synthetic placeholder payloads (the previous version
of this file) no longer produce anything a real decoder can play, since
they were never valid encoded bitstreams to begin with, only
structurally-shaped containers. Fixtures are generated by shelling out to
the `ffmpeg` CLI - test tooling only, matching how testdata/real_av.mp4
and the other real_* fixtures were produced; the engine itself links only
the FFmpeg libraries, never a CLI or an encoder.

video=True writes an H.264 (baseline, ultrafast) + AAC MP4 of the given
duration and resolution. video=False writes an audio-only AAC .m4a. Both
use a real video test pattern and a real sine tone, not silence or a flat
color, so pixel- and sample-level assertions have something genuine to
check against.
"""
import shutil
import subprocess


FFMPEG = shutil.which("ffmpeg")


def _run(args: list) -> None:
    if not FFMPEG:
        raise RuntimeError(
            "ffmpeg not found on PATH; install it to generate test fixtures "
            "(this is sandbox/test tooling only, never shipped)")
    proc = subprocess.run([FFMPEG, "-y", "-loglevel", "error"] + args,
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"ffmpeg fixture generation failed: {proc.stderr}")


def write_mp4(path, video: bool = True, seconds: float = 10.0,
              width: int = 1920, height: int = 1080) -> None:
    """Write a real, decodable MP4 (or audio-only M4A) of the given length."""
    path = str(path)
    if video:
        _run([
            "-f", "lavfi", "-i", f"testsrc=size={width}x{height}:rate=30:duration={seconds}",
            "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}",
            "-c:v", "libx264", "-profile:v", "baseline", "-preset", "ultrafast",
            "-pix_fmt", "yuv420p",
            # A tight, fixed keyframe interval, not libx264's ~250-frame
            # default: a seek near the end of a real-world file snaps back
            # to the nearest keyframe, and a real encoder's normal GOP
            # would leave several seconds of backlog for the pump to
            # drain before the software audio clock (which advances at
            # real wall-clock pace, by design since C.3) catches up to
            # the true end. A test fixture is free to make seeks land
            # close to their target on purpose, which is what an
            # all-intra-ish interval buys here; it is not representative
            # of real file encoding, only of what makes a seek test fast
            # and deterministic.
            "-g", "3", "-keyint_min", "3", "-sc_threshold", "0",
            "-c:a", "aac", "-ar", "44100", "-ac", "2",
            "-shortest", path,
        ])
    else:
        _run([
            "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}",
            "-c:a", "aac", "-ar", "44100", "-ac", "2",
            path,
        ])
